[templates.ambxst]
input_path = "colors.json"
output_path = "~/.cache/ambxst/colors.json"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[templates.waylandar]
input_path = "~/.config/waylandar/theme_template.qml"
output_path = "~/.config/waylandar/frontend/Theme.qml"
